name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test Secrets
      run: echo ${{ secrets.MONGO_URI }}
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ozempic-results-api:$(date +%s) --build-arg \
            mongo_uri=${{ secrets.MONGO_URI }} \
            database_name=${{ secrets.DATABASE_NAME }} \
            bucket_name=${{ secrets.BUCKET_NAME }} \
            s3_access_key_id=${{ secrets.S3_ACCESS_KEY_ID }} \
            s3_secret_access_key=${{ secrets.S3_SECRET_ACCESS_KEY }} \
            s3_endpoint_url=${{ secrets.S3_ENDPONT_URL }} \
            api_key=${{ secrets.API_KEY }}
